name: check aws Access

on: 
  push:
    branches:
      - main

jobs:
  check-access:
    run-on: ubuntu-latest

    steps:
    - name: checkout code
      uses:  action/chekout@v3

    - name: Configure AWS credentials
      uses: aws-action/confirgure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEYID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: "us-east-1"

    - name: verify AWS credentials
      run: aws sts get-caller-identity
      
