name: check aws Access

on: 
  push:
    branches:
      - main

jobs:
  check-access:
    runs-on: ubuntu-latest  # ❗ corrected typo: `run-on` ➝ `runs-on`

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # ❗ corrected `action/chekout` ➝ `actions/checkout`

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2  # ❗ corrected `aws-action/confirgure-aws-credentials` ➝ `aws-actions/configure-aws-credentials`
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: "us-east-1"

    - name: Verify AWS credentials
      run: aws sts get-caller-identity
